### ISSUE TITLE
exec multiplex stream

### ISSUE THREAD

**Issue by mohammadreza-soft74** [clue/php-docker-react#45] opened 2019-02-20 09:49 UTC
hi.
@clue i want to write some string to execStartStream returned stream but it's not writable stream . 
how can i write to this stream?

**Comment by clue** [comment] 2019-03-27 16:49
Yes, I agree and would love to see support for this! If this is something you need for a commercial project and you want to help sponsor or develop this feature, please reach out!

Closing this as a duplicate of #33

**Closed by clue** 2019-03-27 16:49 UTC
